### ISSUE TITLE
Alternate assertion for unhandled events

### ISSUE THREAD

**Issue by reedom** [tamas-p/hisma#17]
At the time of writing, the machine asserts against events either unknown nor of inactive states.

https://github.com/tamas-p/hisma/blob/00a40a977eba25b7c3d3d363c8f975cf340683c5/packages/hisma/lib/src/state_machine.dart#L226-L229

But there are systems either just want to ignore and/or get noticed.
For example, a remote controller can send a various commands to the target machine while it is off. Some may be acceptable while the rest to be ignored.
We can cope with it by defining nop handlers, but it'd be cumbersome.

I think there are three kind of options with unknown/invalid events.
1. just notice it by logger. [The google's hsm](https://github.com/google/hierarchical-state-machine.dart/blob/main/lib/hierarchical_state_machine.dart) employs this method.
2. make the behavior selectable by options, by assertion, throwing exception, or notice by logger, etc.
3. add an ability to handle _errors_ to a state or state machine and let them to choose the subsequent behavior.

**Comment by tamas-p** [comment]
We have all those asserts around as I wanted to start with a strict approach, helping finding problems quick during development of hisma packages (and if you build a release version the asserts are disabled and the behavior is silent progression in most cases  with a return as in the example above). I understand that this is not ideal, so

I like you option 2, where the package user would have the freedom to select the right behavior.
Could be a StateMachine class level member variable that controls this (and maybe additionally something that you can override if you want in a specific StateMachine object). Log would always happen with FINE level and assert would be controlled with a boolean. 

```dart
StateMachine.assertOnError = false;
```

Any thoughts on syntax and default? 

Option 3 could be added later if there's demand.

**Comment by reedom** [comment]
To take advantage of the type system while keeping the code flexible, how about defining a "policy" interface that clients can use to override their preferences? Here's what I suggest:

First, let's define a "policy" interface with a few properties. I'm not sure what to call it yet, so feel free to suggest better names:

```dart
class StateMachinePolicy {
  const StateMachinePolicy({
    this.mismatchEvents,
  });

  final Set<ErrorBehavior>? mismatchEvents;
  // We can have more policy fields
}

enum ErrorBehavior {
  /// Notice the error.
  notice,

  /// Raise an assertion.
  assertion,

  /// Throw an exception.
  exception,
}
```

Now, let's create a utility class for StateMachine implementation that can handle policy overrides:

```dart
// OK to me to have assertion as the default.
const defaultMachinePolicy = {ErrorBehavior.assertion};

// internal class
class ConcretePolicy {
  ConcretePolicy({
    this.mismatchEvents = defaultMachinePolicy,
  });

  ConcretePolicy.from(StateMachinePolicy? policy)
      : this(mismatchEvents: policy?.mismatchEvents ?? defaultMachinePolicy);

  final Set<ErrorBehavior> mismatchEvents;

  ConcretePolicy overrideWith(StateMachinePolicy policy) {
    return ConcretePolicy(
      mismatchEvents: policy.mismatchEvents ?? mismatchEvents,
    );
  }
}
```

We can use this utility class in the StateMachine constructor:

```dart
class StateMachine<S, E, T> {
  // Map storing all state objects indexed by their state ids.
  StateMachine({
    …
    StateMachinePolicy? policy,
  }) : _errorPolicy = ConcretePolicy.from(policy) {
```

And here's an example of how we can use it in the _fire method:

```dart
Future<bool> _fire(E eventId, {required dynamic arg}) async {
    _log.fine('START _internalFire');
    if (_activeStateId == null) {
      if (_errorPolicy.mismatchEvents.contains(ErrorBehavior.assertion)) {
        assert(_activeStateId != null, 'Machine has not been started.');
      }
      if (_errorPolicy.mismatchEvents.contains(ErrorBehavior.notice)) {
        _log.fine('Machine has not been started.');
      }
      if (_errorPolicy.mismatchEvents.contains(ErrorBehavior.exception)) {
        throw HismaMachineNotFoundException('Machine has not been started.');
      }
      return false;
    }
```

If we want to allow clients to override the policy anywhere else, such as in a state or a transition, we can add an additional method to the ConcretePolicy class:

```dart
// internal class
class ConcretePolicy {
  …

  ConcretePolicy overrideWith(StateMachinePolicy? policy) {
    return ConcretePolicy(
      mismatchEvents: policy?.mismatchEvents ?? mismatchEvents,
    );
  }
}
```

And we can consume it like this:

```dart
final mismatchEventsPolicy = _errorPolicy.overrideWith(state.errorPolicy).mismatchEvents;
…
```

Let me know if you have any feedback or questions!

**Comment by tamas-p** [comment]
I like your proposal. Let me play with it a bit and come back soon.

**Comment by reedom** [comment]
This morning, I suddenly realized that creating a concrete class is redundant and we could get by without it. 😃 

```dart
class StateMachinePolicy {
  const StateMachinePolicy({
    this.mismatchEvents,
  });

  const StateMachinePolicy.defaults()
      : mismatchEvents = const {ErrorBehavior.assertion};

  final Set<ErrorBehavior>? mismatchEvents;
}

extension StateMachinePolicyExt on StateMachinePolicy {
  StateMachinePolicy overrideWith(StateMachinePolicy? other) {
    return StateMachinePolicy(
      mismatchEvents: other?.mismatchEvents ?? mismatchEvents,
    );
  }
}
```

While `defaults` populates all of the fields, StateMachine can refer to them safely just by using `!`.
And consolidating default values into the constructor would improve readability.

**Comment by tamas-p** [comment]
Pushed first draft https://github.com/tamas-p/hisma/tree/feature/17/assert-to-policy

Your proposed class is now called ReactionPolicy and the actual handling is also part of class:

https://github.com/tamas-p/hisma/blob/87bdaeb698b65c7e22b9a6175a78bc8512bcc99f/packages/hisma/lib/src/policy.dart#L6-L22

You can configure the policy with both at class level with 
```dart
StateMachine.policy = const ReactionPolicy({Reaction.exception});
```
or at the constructor
```dart
final m = createMachine(const ReactionPolicy({Reaction.exception}));
```

What do you think? 

Also, in your proposal what is the purpose of the `overrideWith` extension method?

**Comment by reedom** [comment]
_I wish we'd have C's preprocessor macro…
so that the head of stacktraces must point at where the issue occurred._

So, my minor concern is the stacktrace, even though the way the `act` does is convenient for library writers…

Plus, I think the order might be better in `log`, `assert`, `exception`.

**Comment by tamas-p** [comment]
> So, my minor concern is the stacktrace, even though the way the `act` does is convenient for library writers…

Indeed, however stacktrace does include the frame from where the the problem is originating, where the `act` was called.
The other option is repetitively c&p the same code to several (currently three) places.
Quick googling shows that they are thinking about introducing  macro to dart - need to read more about it. 

Another thing to fix if we go with the `act` approach is to allow `act` getting message as a function (as you pointed out lazy evaluation of log messages in #18). This would obviously not needed with the c&p approach.

> Plus, I think the order might be better in `log`, `assert`, `exception`.

Yes, make sense. I pushed the fix on this.

**Comment by tamas-p** [comment]
I added a note regarding the ReactionPolicy to the README.md of the hisma package.
Also added some tests and some naming changes.
https://github.com/tamas-p/hisma/tree/feature/17/assert-to-policy

I plan to merge it to master and release it along with the other changes later this week.
Any comments are welcome.

**Comment by reedom** [comment]
I apologize for the delayed response as I was busy with my recent move over the weekend.

Upon reviewing the PR again, I have two concerns:

There is a possibility that the general policy may not necessarily align with all real-world use cases, and it may be desirable to switch policies based on different scenarios.
I'm concerned that allowing policy switching on a per-method basis could introduce unnecessary complexity. Upon reconsidering the overall situation, it appears that this approach may bring about unwanted complications.

Now, in retrospect, I believe it might be best to abandon the use of policies altogether.

In cases where the usage is clearly incorrect, asserts would be appropriate. However, for situations where it varies depending on the use case, I suggest sticking to logging only. We can shift the responsibility of handling issues to the users and encourage them to prevent problems through unit tests and similar approaches.

**Comment by tamas-p** [comment]
>  However, for situations where it varies depending on the use case, I suggest sticking to logging only.

These cases for now are fire on inactive machines and fire an event that is not handled for the active state.
I do found the asserts there useful while working on other packages using hisma, so it makes sense to me to keep them at least optionally.  Default could be logging only resulting the behavior you are proposing.

> I'm concerned that allowing policy switching on a per-method basis could introduce unnecessary complexity. 

With the right default, it would not be used much except by those who needs them - like me to enable asserts.

**Comment by reedom** [comment]
"simplistic" sounds good and it should work at this stage.

**Comment by tamas-p** [comment]
@reedom, sorry for the late action on this, I got too much into refactoring hisma_flutter. Nevertheless these two commits include what we discussed with a slight change to have assertions enabled by default for now (to avoid modifying existing autotests):
d07bee8bf6ebce43286411102de4aea6178d605a
e849d194863a7b9e7c3727d92eac8c97d202cc8c

I wait few days before closing this issue should you have any comments.

**Comment by reedom** [comment]
I'm glad to see your respectful attitude.
It's okay to close this after such a deep consideration. 👍
