### ISSUE TITLE
Getting Visma to load desktop

### ISSUE THREAD

**Issue by macasas** [tamas-p/hisma#22]
I am trying to run a basic app, a new project with just the root from hisma_flutter_discovery, this is why the app screen (top right) in the images are just titles.  But this issue is happening when I run hisma_flutter_discovery app as well.

The left browser is visma as default, 127.0.0.1:4040
The right is visma at default host, but port 1111
Under the browsers, I am showing the code to create the VisualMonitor, either with port: 1111 active or commented in each case.

Images 1 and 2 show iphone simulator, 
I can get the statechart on port 1111 but not 4040
Images 3 and 4 show macos desktop, 
Neither running as default or on 1111 port gives me a statechart, just shows SMWatcher box as per image.

I've noticed the example images are running in a desktop and **this is what I am trying to do, run desktop and see/load the statechart**

I am using a Macbook M1 Pro.  

I am wondering if

- a info.plist permission that I do not know about is missing?
- 4040 is a blocked port
- mac has restricted local permissions on 127.0.0.1
- or if something else is stopping the visma from loading correctly?

Has anyone else had this problem, can hint at why this might be happening or know a solution?

Many thanks.

**iPhone Default**
<img width="1512" alt="iphone default" src="https://github.com/tamas-p/hisma/assets/910082/bd917fb1-bd49-4244-b35e-cec5fd4723c6">

**iPhone 1111**
<img width="1512" alt="iphone 1111" src="https://github.com/tamas-p/hisma/assets/910082/b6749aa7-005a-4b76-b173-f96d6aeee2fa">

**macos Default**
<img width="1512" alt="macos default" src="https://github.com/tamas-p/hisma/assets/910082/4748f82b-14b5-415d-ac12-a2f1afd7925c">

**macos 111**
<img width="1512" alt="macos 1111" src="https://github.com/tamas-p/hisma/assets/910082/e611ac0f-136d-47b9-99c2-8a518bc03251">

**Comment by tamas-p** [comment]
How do you run visma?
Is it something like
```console
docker run -it -p 0.0.0.0:4040:4040 tamasp/visma
```
which did not work for you, and then

```console
docker run -it -p 0.0.0.0:1111:4040 tamasp/visma
```
that at least gave you access to visma.

When you ran visma on :1111 and the VisualMonitor was set to connect :1111 you got this:

**iPhone 1111**
<img width="1512" alt="iphone 1111" src="https://github.com/tamas-p/hisma/assets/910082/b6749aa7-005a-4b76-b173-f96d6aeee2fa">

this is main page is only to show the hierarchy of the state machines.
If you click on the (underscored) machine name (app in the example) you shall get to the state machine diagram.

**Comment by macasas** [comment]
Hi, thanks for your reply.

I installed the docker image, but it has a docker warning, possibly because it says the image if for Ubuntu AMD64 and I am on a mac, not sure, but it tells me the image has poor performance. So I have not been using it.

I tried using the CLI but kept getting “shutting down” errors.

Then I admit, I got distracted because the browser displayed the statechart without visma running in either docker or cli, (how is that possible) when running iphone simulator and going to 127.0.0.1:1111, so I was just doing that expecting it to also work in desktop.  I see now that visma was not even running? But it was displaying. Strange!

Obviously not the way to do it.


So I just downloaded a jar from plantuml.com and run this
visma --port 4040 --plantuml_jar ./plantuml-1.2023.13.jar
"java -jar, ./plantuml-1.2023.13.jar, -Djava.net.useSystemProxies=true, -picoweb:4020:127.0.0.1":
webPort=4020

INFO: 2023-12-14 20:06:52.246503: visma.VisualizationServer: SM PlantUML visualization server stated on InternetAddress('127.0.0.1', IPv4):4040
WARNING: 2023-12-14 20:07:16.007296: visma.VisualizationServer: ERROR: "/favicon.ico" is not found.

So visma is now running.

I am creating the visual monitor in my code.
    (m) => VisualMonitor(
      m,
      host: '127.0.0.1',
      port: 4040,
    ),

Then, I open a browser window and type 127.0.0.1:4040
Now it should work, app is running, it says Loading in browser, but I just get the SM Watcher.

**Comment by tamas-p** [comment]
Where was your program running now? Was it a desktop app, emulator or a real phone?
The program might need to access visma through the IP how it sees your host (laptop).
If that's the case, there are two things to fix:
1) Use that IP address in VisualMonitor as host.
2) Run visma to accept connection on all interfaces (see bellow)

Visma default listens on 127.0.0.1, so only connections from localhost are accepted.
To accept connections from any interfaces you shall add --bind 0.0.0.0 (I might be participating too many security reviews these days, so I set the default to localhost only).

**Comment by macasas** [comment]
flutter app is running in macos desktop
the only host that comes close is 127.0.0.1, which is default
    (m) => VisualMonitor(
      m,
      //host: '127.0.0.1',
      //host: 'localhost',
      //host: '192.168.0.32',
      port: 4040,
    ),

visma is running in CLI
defaults to 127.0.0.1 and then Subscriber disconnects after a minute

visma --port=4040 --plantuml_jar=plantuml-1.2023.13.jar
"java -jar, plantuml-1.2023.13.jar, -Djava.net.useSystemProxies=true, -picoweb:4020:127.0.0.1":
webPort=4020

INFO: 2023-12-14 20:49:53.072161: visma.VisualizationServer: SM PlantUML visualization server stated on InternetAddress('127.0.0.1', IPv4):4040
WARNING: 2023-12-14 20:50:36.842487: visma.VisualizationServer: ERROR: "/favicon.ico" is not found.
INFO: 2023-12-14 20:51:21.299524: visma.BrowserNotifier: Subscriber disconnected.

127.0.0.1:4040 Browser as before SM Watcher
My machine IP, 192.168.0.32 in VisualMonitor gives empty white page


Running visma with bind
visma --port=4040 --plantuml_jar=plantuml-1.2023.13.jar --bind 0.0.0.0
"java -jar, plantuml-1.2023.13.jar, -Djava.net.useSystemProxies=true, -picoweb:4020:127.0.0.1":
webPort=4020

INFO: 2023-12-14 20:58:34.434137: visma.VisualizationServer: SM PlantUML visualization server stated on InternetAddress('0.0.0.0', IPv4):4040
INFO: 2023-12-14 20:58:42.956792: visma.BrowserNotifier: Subscriber disconnected.
INFO: 2023-12-14 20:58:48.274529: visma.BrowserNotifier: Subscriber disconnected.
WARNING: 2023-12-14 20:58:48.541509: visma.VisualizationServer: ERROR: "/favicon.ico" is not found.


App host set to my IP 192.168.0.32 and/or 127.0.0.1
Now ALL of these IPs in browser give SM Watcher only, but still no statechart

Desktop app stopped and run in iOS simulator

Statechart immediately loads with all IPs in browser

I don’t know, but I think it might be a Mac permissions issue.  Had similar in past when trying to access external IPs, sim runs fine, desktop didn’t.  Going to try and find the info.plist keys for that.

**Comment by macasas** [comment]
I've added
	<key>com.apple.security.network.client</key>
	<true/>
to macos Runner.debug and release.entitlement file

Now I have the statechart running with desktop. :-) :-)

These mac permissions .......

Thank you for setting me straight running visma correctly.  That helped a lot :-)

**Comment by tamas-p** [comment]
wow, you found it quick!
I have very limited experience on Mac, but I will test it with your solution when on Mac. Thanks!

Just a note, hisma_flutter is under redesign. Concept will not change, but hacks to be removed.
In the other packages I am not aware of issues.

**Comment by macasas** [comment]
I was thinking it was related to visma until you started talking about bindings and ip addresses and that made me think of another project where iOS was running fine but macos kept erroring out, and it was this entitlement key. Just copied them from that project to try. I'm sure there's a bunch of them, but who knows what they all do?

This is now working as needed I'm going to deep dive into nested regions tomorrow as well as navigation machines linking off somehow to app state machines. Hoping to demo a MVP by early next week so fingers crossed my rough sketch theory smoothly merges with your code, I really like the separation so far.

Will certainly be interested in what changes.

Thanks for your help

**Comment by tamas-p** [comment]
I keep this open till I add a note to README.md about your finding for Mac users.

**Comment by tamas-p** [comment]
I would like to add a warning to the [README.md](https://github.com/tamas-p/hisma/blob/master/packages/hisma_visual_monitor/README.md) of the visual_monitor package for Mac users. Being short on time testing it on Mac, could you review the warning text?

> **Warning**
> When using VisualMonitor in a MacOS desktop application you shall add
> ```xml
> <key>com.apple.security.network.client</key><true/>
>```
> to your Runner.debug and release.entitlement files of your project to allow connectivity to [visma](https://github.com/tamas-p/hisma/tree/master/packages/visma).

**Comment by macasas** [comment]
Just some minor word changes and the file names, otherwise good.

Warning
When using VisualMonitor in a MacOS desktop application you need to add

<key>com.apple.security.network.client</key><true/>

to your macos/Runner/DebugProfile.entitlements and macos/Runner/Release.entitlements files of your project to allow connectivity to [visma](https://github.com/tamas-p/hisma/tree/master/packages/visma).

**Comment by macasas** [comment]
Sounds good.  Always happy to test things on mac for you.

**Comment by tamas-p** [comment]
Note added with commit 1d65dbc9e8407dd2dc1113ac794cd4223dd7831b.
See [README.md](https://github.com/tamas-p/hisma/tree/master/packages/hisma_visual_monitor).
